### ISSUE TITLE
符数计算有点问题，双风符数某些规则可以取4

### ISSUE THREAD

**Issue by drrr5052** [WaSuper/Mahjong#10]
例如东一庄家223344m67s11222z自摸58s，雀魂/天凤规则的话是2番40符 自摸20+双风4+幺九暗刻8=32符，ML规则则是取2符。
现在计算器计算的结果是2番30符。希望能加一个选择的地方，谢谢大佬

**Comment by WaSuper** [comment]
查了一下还真有这个规则，我现在在做完善十七步和三人麻将，等我下次更新应该可以一起加上去啦，不过业余时间做得比较慢，要等等哦

**Comment by drrr5052** [comment]
最近在学算符才注意到这个问题，不是很急，多谢大佬

**Comment by WaSuper** [comment]
> 最近在学算符才注意到这个问题，不是很急，多谢大佬

更新啦，已修复bug
