### ISSUE TITLE
希望能增加三麻模式~

### ISSUE THREAD

**Issue by bearycutebear** [WaSuper/Mahjong#11]
疫情严重，筹齐三个人就很不容易了，希望能有三麻模式。

**Comment by WaSuper** [comment]
在写了在写了，应该下个月能出货...吧...

**Comment by bearycutebear** [comment]
> 在写了在写了，应该下个月能出货...吧...

辛苦啦~

**Comment by WaSuper** [comment]
> > 在写了在写了，应该下个月能出货...吧...
> 
> 辛苦啦~

鸽了很久，三麻终于出货了，可以先试试水→_→
（建议先把记录下载保存下先，不知道会不会有没测出来的bug...）

**Comment by bearycutebear** [comment]
> > > 在写了在写了，应该下个月能出货...吧...
> > 
> > 
> > 辛苦啦~
> 
> 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）

谢谢大大！这就下载试试！！！

**Comment by bearycutebear** [comment]
> > > 在写了在写了，应该下个月能出货...吧...
> > 
> > 
> > 辛苦啦~
> 
> 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）

大大.....对战记录经常莫名其妙丢失，，，

**Comment by WaSuper** [comment]
> > > > 在写了在写了，应该下个月能出货...吧...
> > > 
> > > 
> > > 辛苦啦~
> > 
> > 
> > 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）
> 
> 大大.....对战记录经常莫名其妙丢失，，，

怎么个丢失法？是对战完后不能保存看不到记录，还是过几天记录不见了？

**Comment by bearycutebear** [comment]
> > > > > 在写了在写了，应该下个月能出货...吧...
> > > > 
> > > > 
> > > > 辛苦啦~
> > > 
> > > 
> > > 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）
> > 
> > 
> > 大大.....对战记录经常莫名其妙丢失，，，
> 
> 怎么个丢失法？是对战完后不能保存看不到记录，还是过几天记录不见了？

对战完成看不到发生一次，然后过几天也丢失了一场记录，

**Comment by WaSuper** [comment]
> > > > > > 在写了在写了，应该下个月能出货...吧...
> > > > > 
> > > > > 
> > > > > 辛苦啦~
> > > > 
> > > > 
> > > > 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）
> > > 
> > > 
> > > 大大.....对战记录经常莫名其妙丢失，，，
> > 
> > 
> > 怎么个丢失法？是对战完后不能保存看不到记录，还是过几天记录不见了？
> 
> 对战完成看不到发生一次，然后过几天也丢失了一场记录，

是同一种模式吗？四麻、三麻的记录是分开的，不在一起显示
如果实在不行，看看把全部玩家和对战记录导出来后，删掉app再重新安装导入进去看看行不行

**Comment by bearycutebear** [comment]
> 



> > > > > > > 在写了在写了，应该下个月能出货...吧...
> > > > > > 
> > > > > > 
> > > > > > 辛苦啦~
> > > > > 
> > > > > 
> > > > > 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）
> > > > 
> > > > 
> > > > 大大.....对战记录经常莫名其妙丢失，，，
> > > 
> > > 
> > > 怎么个丢失法？是对战完后不能保存看不到记录，还是过几天记录不见了？
> > 
> > 
> > 对战完成看不到发生一次，然后过几天也丢失了一场记录，
> 
> 是同一种模式吗？四麻、三麻的记录是分开的，不在一起显示 如果实在不行，看看把全部玩家和对战记录导出来后，删掉app再重新安装导入进去看看行不行

啊，，，我是在一起现实的，，，同一页有三麻也有4麻。。

**Comment by bearycutebear** [comment]
![9CAE3DAC922478C34EA77E61E6080677](https://user-images.githubusercontent.com/119110393/230909287-7acc5ed6-ae54-4c91-ba5d-8e96a87131de.jpg)

**Comment by WaSuper** [comment]
> > 
> 
> > > > > > > > 在写了在写了，应该下个月能出货...吧...
> > > > > > > 
> > > > > > > 
> > > > > > > 辛苦啦~
> > > > > > 
> > > > > > 
> > > > > > 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）
> > > > > 
> > > > > 
> > > > > 大大.....对战记录经常莫名其妙丢失，，，
> > > > 
> > > > 
> > > > 怎么个丢失法？是对战完后不能保存看不到记录，还是过几天记录不见了？
> > > 
> > > 
> > > 对战完成看不到发生一次，然后过几天也丢失了一场记录，
> > 
> > 
> > 是同一种模式吗？四麻、三麻的记录是分开的，不在一起显示 如果实在不行，看看把全部玩家和对战记录导出来后，删掉app再重新安装导入进去看看行不行
> 
> 啊，，，我是在一起显示的，，，同一页有三麻也有4麻。。

这样子，应该是数据升级有问题...
你打开右上角的关于页面，然后点一下摆动的那个图标，然后会把数据库拷贝到你的存储首页上，你把那个mahjong.db的文件发我看看，还有把导出的对战记录的xls文件也发我看看是不是有问题

**Comment by WaSuper** [comment]
> ![9CAE3DAC922478C34EA77E61E6080677](https://user-images.githubusercontent.com/119110393/230909287-7acc5ed6-ae54-4c91-ba5d-8e96a87131de.jpg)

不过你这种情况应该要重新安装了，数据库升级出错了，不过app支持一键导出导入，重新安装也什么关系，不过记录多的时候导入会卡一阵子，要等一下不要关掉，导出的三麻数据应该也要修改一下再导入才行，main_type那一列要改成1

**Comment by bearycutebear** [comment]
> > > 
> > 
> > 
> > > > > > > > > 在写了在写了，应该下个月能出货...吧...
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 辛苦啦~
> > > > > > > 
> > > > > > > 
> > > > > > > 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）
> > > > > > 
> > > > > > 
> > > > > > 大大.....对战记录经常莫名其妙丢失，，，
> > > > > 
> > > > > 
> > > > > 怎么个丢失法？是对战完后不能保存看不到记录，还是过几天记录不见了？
> > > > 
> > > > 
> > > > 对战完成看不到发生一次，然后过几天也丢失了一场记录，
> > > 
> > > 
> > > 是同一种模式吗？四麻、三麻的记录是分开的，不在一起显示 如果实在不行，看看把全部玩家和对战记录导出来后，删掉app再重新安装导入进去看看行不行
> > 
> > 
> > 啊，，，我是在一起显示的，，，同一页有三麻也有4麻。。
> 
> 这样子，应该是数据升级有问题... 你打开右上角的关于页面，然后点一下摆动的那个图标，然后会把数据库拷贝到你的存储首页上，你把那个mahjong.db的文件发我看看，还有把导出的对战记录的xls文件也发我看看是不是有问题


> > > 
> > 
> > 
> > > > > > > > > 在写了在写了，应该下个月能出货...吧...
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 辛苦啦~
> > > > > > > 
> > > > > > > 
> > > > > > > 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）
> > > > > > 
> > > > > > 
> > > > > > 大大.....对战记录经常莫名其妙丢失，，，
> > > > > 
> > > > > 
> > > > > 怎么个丢失法？是对战完后不能保存看不到记录，还是过几天记录不见了？
> > > > 
> > > > 
> > > > 对战完成看不到发生一次，然后过几天也丢失了一场记录，
> > > 
> > > 
> > > 是同一种模式吗？四麻、三麻的记录是分开的，不在一起显示 如果实在不行，看看把全部玩家和对战记录导出来后，删掉app再重新安装导入进去看看行不行
> > 
> > 
> > 啊，，，我是在一起显示的，，，同一页有三麻也有4麻。。
> 
> 这样子，应该是数据升级有问题... 你打开右上角的关于页面，然后点一下摆动的那个图标，然后会把数据库拷贝到你的存储首页上，你把那个mahjong.db的文件发我看看，还有把导出的对战记录的xls文件也发我看看是不是有问题

[表格和日志.zip](https://github.com/WaSuper/Mahjong/files/11199331/default.zip)

**Comment by WaSuper** [comment]
> > > > 
> > > 
> > > 
> > > > > > > > > > 在写了在写了，应该下个月能出货...吧...
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 辛苦啦~
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）
> > > > > > > 
> > > > > > > 
> > > > > > > 大大.....对战记录经常莫名其妙丢失，，，
> > > > > > 
> > > > > > 
> > > > > > 怎么个丢失法？是对战完后不能保存看不到记录，还是过几天记录不见了？
> > > > > 
> > > > > 
> > > > > 对战完成看不到发生一次，然后过几天也丢失了一场记录，
> > > > 
> > > > 
> > > > 是同一种模式吗？四麻、三麻的记录是分开的，不在一起显示 如果实在不行，看看把全部玩家和对战记录导出来后，删掉app再重新安装导入进去看看行不行
> > > 
> > > 
> > > 啊，，，我是在一起显示的，，，同一页有三麻也有4麻。。
> > 
> > 
> > 这样子，应该是数据升级有问题... 你打开右上角的关于页面，然后点一下摆动的那个图标，然后会把数据库拷贝到你的存储首页上，你把那个mahjong.db的文件发我看看，还有把导出的对战记录的xls文件也发我看看是不是有问题
> 
> > > > 
> > > 
> > > 
> > > > > > > > > > 在写了在写了，应该下个月能出货...吧...
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 辛苦啦~
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 鸽了很久，三麻终于出货了，可以先试试水→_→ （建议先把记录下载保存下先，不知道会不会有没测出来的bug...）
> > > > > > > 
> > > > > > > 
> > > > > > > 大大.....对战记录经常莫名其妙丢失，，，
> > > > > > 
> > > > > > 
> > > > > > 怎么个丢失法？是对战完后不能保存看不到记录，还是过几天记录不见了？
> > > > > 
> > > > > 
> > > > > 对战完成看不到发生一次，然后过几天也丢失了一场记录，
> > > > 
> > > > 
> > > > 是同一种模式吗？四麻、三麻的记录是分开的，不在一起显示 如果实在不行，看看把全部玩家和对战记录导出来后，删掉app再重新安装导入进去看看行不行
> > > 
> > > 
> > > 啊，，，我是在一起显示的，，，同一页有三麻也有4麻。。
> > 
> > 
> > 这样子，应该是数据升级有问题... 你打开右上角的关于页面，然后点一下摆动的那个图标，然后会把数据库拷贝到你的存储首页上，你把那个mahjong.db的文件发我看看，还有把导出的对战记录的xls文件也发我看看是不是有问题
> 
> [表格和日志.zip](https://github.com/WaSuper/Mahjong/files/11199331/default.zip)

额，数据库好像没看到数据？表格里确实是MainType那一列出错了，0代表四麻，1代表三麻，你可以改一下再导进去
至于APP应该是升级出BUG了，应该还是要删掉重装一下
![修改](https://user-images.githubusercontent.com/13520244/231154418-e42f44c3-e7c9-402e-a64c-4efd07dc4c18.png)

**Comment by WaSuper** [comment]
> > 
> 
> [mahjong(1).zip](https://github.com/WaSuper/Mahjong/files/11201888/mahjong.1.zip) 这次呢

 还是没有看到对战数据...
我发个工具给你，你可以自己打开看看，MjResult里面就是所有对局数据，你导出文件是空的，不知道是不是数据库损坏了
你有试过重新安装再导入xls文件看看能正常显示吗？或者你找另一台手机试验一下先？

[SQLiteStudio3.1.1.zip](https://github.com/WaSuper/Mahjong/files/11202069/SQLiteStudio3.1.1.zip)
![对战数据](https://user-images.githubusercontent.com/13520244/231209118-22e3ce16-222d-4274-a7a2-2059bb4cd73b.png)

**Comment by bearycutebear** [comment]
> > > 
> > 
> > 
> > [mahjong(1).zip](https://github.com/WaSuper/Mahjong/files/11201888/mahjong.1.zip) 这次呢
> 
> 还是没有看到对战数据... 我发个工具给你，你可以自己打开看看，MjResult里面就是所有对局数据，你导出文件是空的，不知道是不是数据库损坏了 你有试过重新安装再导入xls文件看看能正常显示吗？或者你找另一台手机试验一下先？
> 
> [SQLiteStudio3.1.1.zip](https://github.com/WaSuper/Mahjong/files/11202069/SQLiteStudio3.1.1.zip) ![对战数据](https://user-images.githubusercontent.com/13520244/231209118-22e3ce16-222d-4274-a7a2-2059bb4cd73b.png)

绝了，我自己打开也是空白，明明文件是最新导出的

**Comment by bearycutebear** [comment]
> > > 
卸载重装了。修改完表格导入是正常的，现在就看下次记录的时候会不会出现bug了

**Comment by bearycutebear** [comment]
> > > > >
> > 
> > 
> > 卸载重装了。修改完表格导入是正常的，现在就看下次记录的时候会不会出现bug了
> 
> 可以自己随便点几次对局看看能不能正确保存，反正记录点长按可以自己删掉的

嗯，，我晚点的，，白天那个手机不在身边。。
