### ISSUE TITLE
反馈两个bug

### ISSUE THREAD

**Issue by mxzs10** [WaSuper/Mahjong#14]
1. 对局结束后如果场供里还有立直棒，没有给到一位，会导致所有人pt加起来不为0
![IMG_4310](https://github.com/WaSuper/Mahjong/assets/62588300/999cb74d-31a0-4c87-a732-b78d8e5fac30)

2. 对战入口的选人界面，如果玩家列表太长会点不到下面的确认键
![IMG_4311](https://github.com/WaSuper/Mahjong/assets/62588300/f8c6d093-1b74-411e-bf13-d6d9910b6577)

**Comment by WaSuper** [comment]
发个临时版本改了这个bug，如果急用可以先用，正式更新还要等等（升级前注意备份数据）
[Saki_v2.1.2_build230802.zip](https://github.com/WaSuper/Mahjong/files/12238742/Saki_v2.1.2_build230802.zip)

**Comment by mxzs10** [comment]
哇，感谢，好快的修复！

新版本运行正常，不过好像以前那些丢了pt的对局没法修复了。

还有个建议：希望可以在个人数据那里加入平均打点和平均铳点一类的数据~

**Comment by mxzs10** [comment]
<img width="897" alt="image" src="https://github.com/WaSuper/Mahjong/assets/62588300/190eef53-487b-415c-87f4-7ff1c380d17c">
新版本v2.1.2好像有新的bug，南四如果没有流局，也会把点棒给到一位

**Comment by WaSuper** [comment]
> <img alt="image" width="897" src="https://user-images.githubusercontent.com/62588300/261858835-190eef53-487b-415c-87f4-7ff1c380d17c.png"> 新版本v2.1.2好像有新的bug，南四如果没有流局，也会把点棒给到一位

之前玩家起飞后结束没有将立直棒清空，现在加多了一个步骤忘了将这个处理了，再重新发个版本给你试试
[Saki_v2.1.3_build230821.zip](https://github.com/WaSuper/Mahjong/files/12390681/Saki_v2.1.3_build230821.zip)

**Comment by ttcwws** [comment]
还是有个bug，如果有人被击飞了且不带击飞，他立直不了，但是应该可以立的

**Comment by WaSuper** [comment]
> 还是有个bug，如果有人被击飞了且不带击飞，他立直不了，但是应该可以立的

已修复，可以下载新版本看看
