### ISSUE TITLE
立直bgm似乎不能导出？

### ISSUE THREAD

**Issue by T0k1ta** [WaSuper/Mahjong#16]
我看导出的xls文件里没有相关信息

**Comment by WaSuper** [comment]
导出玩家信息后会看到有五个分表的，其中audio那里就有设置的音频信息。
![20231027141650](https://github.com/WaSuper/Mahjong/assets/13520244/4009d804-7345-45db-bb92-d0c1ffbc76bc)

**Comment by T0k1ta** [comment]
瞎了，我的
