### ISSUE TITLE
大车轮显示问题

### ISSUE THREAD

**Issue by XiaoRannn** [WaSuper/Mahjong#2]
大车轮显示成大竹林

**Comment by WaSuper** [comment]
请问在哪个页面显示错了，我看我的字符串没有写错的喔

**Comment by XiaoRannn** [comment]
查看役种那里
![1626938802391](https://user-images.githubusercontent.com/87789808/126603417-611dbb92-3fdb-4411-a857-acf5c3665c21.jpg)

**Comment by WaSuper** [comment]
哈哈，以为没人看这里，想不到还有个火眼金睛，Nice！

**Comment by XiaoRannn** [comment]
本来想自己写一个的，就上网搜了搜居然能找到。看到工程量这么大就放弃了

**Comment by WaSuper** [comment]
上班摸鱼做的，小项目，小项目→_→

**Comment by XiaoRannn** [comment]
我最近刚学Android，Java基础也不咋样，请问有什么学习的建议吗

**Comment by XiaoRannn** [comment]
我最近刚学Android，Java基础也不咋样，请问有什么学习的建议吗

**Comment by WaSuper** [comment]
不做程序猿好多年啦，建议脱坑，保护头发，哈哈

**Comment by XiaoRannn** [comment]
我还是在读大学生，还在为Android大作业发愁 ￣□￣｜｜
