### ISSUE TITLE
开始游戏后立直闪退

### ISSUE THREAD

**Issue by Outvoker** [WaSuper/Mahjong#3]
开始游戏后上下两家立直会闪退，左右不会
如果切换视角了 还是上下闪退

**Comment by WaSuper** [comment]
我用了几年都没发现这个问题喔，可否详细说下怎么操作，或者有设置了什么音频吗，或者是手机型号问题？
或者调试一下打印一下错误信息看看？

**Comment by Giles2000** [comment]
是的 怎么调试这个问题？
红米k30 pro
miui 13
没有导入语音包 也没启用
我和对家立就崩溃 退出到首页
左右两家立没问题
而且导入雀魂语音包 默认只导入了第一的那一个语音 其他 立直 胡牌和自摸的语音不晓得为什么都没打开

**Comment by WaSuper** [comment]
> 是的 怎么调试这个问题？ 红米k30 pro miui 13 没有导入语音包 也没启用 我和对家立就崩溃 退出到首页 左右两家立没问题 而且导入雀魂语音包 默认只导入了第一的那一个语音 其他 立直 胡牌和自摸的语音不晓得为什么都没打开
[Saki_v1.3.0_beta220720.zip](https://github.com/WaSuper/Mahjong/files/9146175/Saki_v1.3.0_beta220720.zip)
你安装下我这个测试版本，然后再操作一次让程序崩溃，然后找到目录/Mahjong/crash，里面会生成一个崩溃记录文件，你发这个文件给我就可以了，邮箱：summerlee9527@foxmail.com

**Comment by Giles2000** [comment]
> > 你安装下我这个测试版本，然后再操作一次让程序崩溃，然后找到目录/Mahjong/crash，里面会生成一个崩溃记录文件，你发这个文件给我就可以了，邮箱：[summerlee9527@foxmail.com](mailto:summerlee9527@foxmail.com)

已经发送

**Comment by WaSuper** [comment]
> > > 你安装下我这个测试版本，然后再操作一次让程序崩溃，然后找到目录/Mahjong/crash，里面会生成一个崩溃记录文件，你发这个文件给我就可以了，邮箱：[summerlee9527@foxmail.com](mailto:summerlee9527@foxmail.com)
> 
> 已经发送

修改了一下bug，发你邮箱了，原来图片素材被系统回收了，部分手机系统优化真厉害...

**Comment by Giles2000** [comment]
> 

好了。

**Comment by WaSuper** [comment]
> 有点疑问啊。 就是界面做成正方形吗？以屏幕短边为长度的正方形
> 
> ```
> -------------------                 -------------------  
> |         西           |            |                        | 
> |                      |            |                        |            
> |                      |            |          西          |            
> |                      |            |                       |            
> |                      |            |                        |            
> |北                   南| --------> |北                     南|            
> |                      |            |                       |            
> |                      |            |                       |            
> |                      |            |          东          |            
> |                      |            |                        |            
> |        东            |            |                       |            
> -------------------                 ----------------------
> ```
> 
> 这样会不会看着更整齐一些。当然不做也行。、 感谢app的分享

可以是可以，但是靠近屏幕边界操作的话应该会更顺手，距离感把控会更好吧...
还有就是，习惯了...
