### ISSUE TITLE
暗杠九莲

### ISSUE THREAD

**Issue by XiaoRannn** [WaSuper/Mahjong#4]
居然更新了！好耶
关于开暗杠后可以胡九莲，感觉有点问题

![qq_pic_merged_1640954013805](https://user-images.githubusercontent.com/87789808/147823823-e213be00-364c-4996-a912-aced2210cbf0.jpg)
![qq_pic_merged_1640953951259](https://user-images.githubusercontent.com/87789808/147823830-55a9ac49-0e4d-4b69-a74e-bbd5d703a0fb.jpg)

**Comment by WaSuper** [comment]
大哥，你是专职测试的吗？这么勤快→_→
你竟然要一个面基麻将还没胡过役满人去发现役满的bug？太残忍了[泪留满面]

**Comment by XiaoRannn** [comment]
因为线下面麻会经常玩 偶然发现了这个bug

**Comment by WaSuper** [comment]
什么时候才可以轮到我“偶然”发现这个役满bug呢...

**Comment by XiaoRannn** [comment]
如果不是小学期没学安卓，我也不会发现这个软件  哈哈 主要是对面麻新手太友好了

**Comment by WaSuper** [comment]
现在主要是按键有点紧密和小，点立直有点不灵，下次更新将会重新设计一下界面，有什么好建议可以提一下
