### ISSUE TITLE
牌局结束时卡死的问题

### ISSUE THREAD

**Issue by IsaacLuo** [WaSuper/Mahjong#5]
牌局结束时整个画面变暗，无任何操作选项。只能强制退出
![Screenshot_20220103-093937_Saki](https://user-images.githubusercontent.com/3862134/147916834-49aaa922-91d6-4dfd-a1ce-5d66a4616792.jpg)

**Comment by WaSuper** [comment]
请问是固定出现还是只出现这一次？我记得之前修复过一次，之后再没出现过

**Comment by IsaacLuo** [comment]
在我手机（samsung SM-G965F，系统Android 10）上固定出现。

打完南四局以后必然死机，没有对话框弹出。强制退出并重启后，如果选择恢复牌局，重新结算后也会卡在"西一局“的画面上。

如果是有人负分击飞，同样死机，没有对话框弹出。强制退出并重新进入app，并恢复牌局后会询问有人被击飞是否结束游戏，选择是的话能正常结束。

以上两点都是每次必然发生，我是从github release上下载的版本（Saki_v1.1.0_build211230）

**Comment by WaSuper** [comment]
由于我的手机（一加7T，系统android 11）重现不了这种情况，可能是一些手机的一些系统设置问题，我这里弄了改了一点代码的版本，用Handler来打开对话框，你试试可不可以？
或者你打开开发者模式里的显示布局边界选项，看看变暗的那个界面有没有对话框的布局存在？
或者你下载代码用自己的手机试试其他方法？
由于不是专职码农，没有多余的手机测试，就这样
[Saki_v1.1.0_beta_v1.zip](https://github.com/WaSuper/Mahjong/files/7820857/Saki_v1.1.0_beta_v1.zip)

**Comment by IsaacLuo** [comment]
谢谢，很神奇的就是我打开开发者模式并显示布局边界以后，居然无法再重现这种情况了，然后即便是关闭开发者模式，也无法再现。所以暂时没有办法继续测试了。。。

不过我觉得，如果按返回键能够等效于选择“否”的话，就不会陷入卡死的境地。也就不需要重启app（之后需要结束牌局的时候可以在界面里选择“立即结束”）从而绕开卡死的可能性。
