### ISSUE TITLE
马点计算好像有点问题

### ISSUE THREAD

**Issue by mxzs10** [WaSuper/Mahjong#6]
马点默认设置成15,5,-5,-15，但最终结算的时候好像就变成30,0,-10,-20

**Comment by mxzs10** [comment]
哦我懂了，看了一下代码，原来是有头名赏，请问这个设置可以关掉吗

**Comment by WaSuper** [comment]
现在还没更新代码，暂时还不能关，下次更新的时候可以设置为0
其他功能还在修改中，最近主业比较忙，副业暂时没法更新啦→_→

**Comment by WaSuper** [comment]
> 哦我懂了，看了一下代码，原来是有头名赏，请问这个设置可以关掉吗

已更新，可以在设置页面将5000设为0
