### ISSUE TITLE
希望能加入横屏适配

### ISSUE THREAD

**Issue by iMissWonder** [WaSuper/Mahjong#7]
app非常好用，但是我平常都是投屏在电视上使用，所以希望能够加入横屏适配，有偿支持~ QQ 554633404

**Comment by WaSuper** [comment]
兄弟，论坛那边很少上去，没怎么留意哈...
这app是上班摸鱼弄的（主业不是码农），所以更新没那么快哈，有的话会马上发布的
感谢支持，多帮我宣传一下就行啦，毕竟是雀友福利
不过投屏使用也是没想到啊，毕竟我的麻将桌旁没有电视机...

**Comment by WaSuper** [comment]
> 是不是不兼容安卓12呀。。我用红米k40会闪退，用安卓11的小米9就不会

本人手机也是安卓11，没试过12啊，有空找个手机试试

**Comment by WaSuper** [comment]
> app非常好用，但是我平常都是投屏在电视上使用，所以希望能够加入横屏适配，有偿支持~ QQ 554633404
[Saki_v1.3.0_build220819.zip](https://github.com/WaSuper/Mahjong/files/9380643/Saki_v1.3.0_build220819.zip)
兄弟，最近有空加了个横屏模式，可以先试试尝鲜版（可能有未知bug哦，记得先保存数据，有问题可以留言）

**Comment by WaSuper** [comment]
> app非常好用，但是我平常都是投屏在电视上使用，所以希望能够加入横屏适配，有偿支持~ QQ 554633404

兄弟，最近有空加了个横屏模式，可以先试试尝鲜版（可能有未知bug哦，记得先保存数据，有问题可以留言）
[Saki_v1.3.0_build220819.zip](https://github.com/WaSuper/Mahjong/files/9380701/Saki_v1.3.0_build220819.zip)

**Comment by iMissWonder** [comment]
太好了，感谢大佬
下次疯狂星期四v你50

发自我的iPhone
