### ISSUE TITLE
游戏类型注释有错误

### ISSUE THREAD

**Issue by mxzs10** [WaSuper/Mahjong#8]
MjResult.java里的49行注释好像有错误：游戏类型:1->东风战，2->半庄战，4->全庄战
感觉应该是：0->东风战，1->半庄战，3->全庄战

**Comment by WaSuper** [comment]
对的，注释打错了，老哥看得挺认真的嘛...

**Comment by mxzs10** [comment]
> 对的，注释打错了，老哥看得挺认真的嘛...

哈哈因为以前战绩里面有头名赏，需要手动修改xls文件里的pt，无意中发现的→_→
